### ISSUE TITLE
Failed to initialize Kubernetes master node...

### ISSUE THREAD

**Issue by rhkjyn** [Orientsoft/kubekit#1]
centos 7.3下安装出错，报如下错误，请问如何解决
[root@localhost kubekit-release]# ./kubekit init 10.72.8.242

 ___  __        ___  ___      ________      _______       ___  __        ___      _________
|\  \|\  \     |\  \|\  \    |\   __  \    |\  ___ \     |\  \|\  \     |\  \    |\___   ___\
\ \  \/  /|_   \ \  \\\  \   \ \  \|\ /_   \ \   __/|    \ \  \/  /|_   \ \  \   \|___ \  \_|
 \ \   ___  \   \ \  \\\  \   \ \   __  \   \ \  \_|/__   \ \   ___  \   \ \  \       \ \  \
  \ \  \\ \  \   \ \  \\\  \   \ \  \|\  \   \ \  \_|\ \   \ \  \\ \  \   \ \  \       \ \  \
   \ \__\\ \__\   \ \_______\   \ \_______\   \ \_______\   \ \__\\ \__\   \ \__\       \ \__\
    \|__| \|__|    \|_______|    \|_______|    \|_______|    \|__| \|__|    \|__|        \|__|

KubeKit V0.1.0 ⓒ  OrientSoft 2017

Initialization process started, with kubernetes master IP: 10.72.8.242

✔ HTTP file server listening at: 0.0.0.0:8000

Start to install docker engine...
(1/2) Start to install docker...

✔ Docker engine installed...

Start to initialize Kubernetes master node...

(1/6) Start to load images for Kubernetes master...
Exit Status: 1

✖ Failed to initialize Kubernetes master node...

[root@localhost kubekit-release]# ls
assets  install.log  kubekit  LICENSE  package  packages  README.md  templates
[root@localhost kubekit-release]# rm packages/ -rf
[root@localhost kubekit-release]# uname -sr
Linux 3.10.0-514.el7.x86_64

[root@localhost kubekit-release]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by cd1989929** [comment]
解决了没？
