### ISSUE TITLE
unable to load client CA file /etc/kubernetes/pki/ca.crt

### ISSUE THREAD

**Issue by cf532088799** [Orientsoft/kubekit#10]
你好，有几个问题需要和你确认一下：
1、我使用的是Centos 7.1708最小化安装，在执行docker安装步骤的时候会出现依赖的问题，必须通过挂载内网镜像yum源解决才能继续后面的脚本命令；
2、解决上述问题之后，继续安装到master初始化的第4步出现退出，查看系统日志发现kubeadm找不到认证文件，查看相应目录下确实没有生成相应的文件，不清楚ssl认证文件的执行步骤，我在master.sh中并没有找到，不知道是什么原因导致的。

**Comment by TimothyYe** [comment]
@cf532088799 

你好，是否有下载对应操作系统的离线安装包？
第二个问题，有没有比较详细的日志？

**Comment by cf532088799** [comment]
你好，相同的镜像1708，相同的kubekit和packge，在笔记本的vmware workstation的虚拟机中可以正常部署kubernetes集群，可是在公司的服务器中的vmware workstation中创建的虚拟机中却不能。报错主要有以下几点：
1、ERROR:Storage is already configured with o driver，can·t configure it with devicemapper。To override，remove /etc/sysconfig/docker-storage and retry
是需要把这个文件删除掉再试下吗？

**Comment by TimothyYe** [comment]
@cf532088799 理论上既然是相同的镜像，应该不会有这种问题的，难道环境有差异？

**Comment by cf532088799** [comment]
同时与以下的一个报错：
error：unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt:no such file or directory
kubelet.service :main process exited,code=exited,status=1/Failure
Unit kubelet.service entered failed state
kubelet .service failed
kubelet.service holdoff time over,scheduling restart

**Comment by cf532088799** [comment]
@TimothyYe 和笔记本中虚拟机唯一的差异在于IP地址，笔记本中是IP是192.168.101.0网段的地址
服务器中的虚拟机是172.25.2.0网段的地址

**Comment by cf532088799** [comment]
还有就是公司的服务器是不同外网的。

**Comment by TimothyYe** [comment]
应该跟IP关系不大，另外，没有外网应该也不影响安装才对

**Comment by cf532088799** [comment]
我看mast.sh中有一个需要联网获取kubeadm的命令，您确认一下是否需要

**Comment by cf532088799** [comment]
脚本中具体的内容
#kubeadm需要联网去找最新版本
echo “$HTTP_SERVER storage.gooleapis.com”>>/etc/hosts

**Comment by TimothyYe** [comment]
@cf532088799  kubeadm会初始化kubelet，并从gcr.io拖取镜像，不过本地镜像已经事先导入，本地已有gcr.io的镜像，所以kubeadm初始化的时候，已经不需要访问网络

**Comment by TimothyYe** [comment]
echo “$HTTP_SERVER storage.gooleapis.com”>>/etc/hosts  这是让storage.googleapis.com 默认解析到局域网内网中的K8S master那台机器去，所以不会访问外网

**Comment by cf532088799** [comment]
我也觉得很纳闷，能否指明一下kubernetes CA文件的生成步骤，错误就是指CA文件不存在，在本地相应目录也确实没有相应的文件，所以想确认一下是不是CA生成的时候出的错

**Comment by cf532088799** [comment]
你好，经验证，相同的包，相同的系统，相同操作，在通外网的情况下是正常的，可以再优化一下脚本吗，肯定有哪里是需要外网需求的。

**Comment by a198720** [comment]
ov  8 16:26:09 jdu4e00u53f7 systemd: Started kubelet: The Kubernetes Node Agent.
Nov  8 16:26:09 jdu4e00u53f7 systemd: Starting kubelet: The Kubernetes Node Agent...
Nov  8 16:26:09 jdu4e00u53f7 kubelet: I1108 16:26:09.584593    6625 feature_gate.go:156] feature gates: map[]
Nov  8 16:26:09 jdu4e00u53f7 kubelet: I1108 16:26:09.584683    6625 controller.go:114] kubelet config controller: starting controller
Nov  8 16:26:09 jdu4e00u53f7 kubelet: I1108 16:26:09.584690    6625 controller.go:118] kubelet config controller: validating combination of defaults and flags
Nov  8 16:26:09 jdu4e00u53f7 kubelet: error: unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory
Nov  8 16:26:09 jdu4e00u53f7 systemd: kubelet.service: main process exited, code=exited, status=1/FAILURE
Nov  8 16:26:09 jdu4e00u53f7 systemd: Unit kubelet.service entered failed state.
Nov  8 16:26:09 jdu4e00u53f7 systemd: kubelet.service failed.

我也出现类似情况,我的文件结构:
kubekit
├── assets
│   ├── css
│   ├── img
│   ├── js
│   └── libs
├── package
│   ├── images
│   ├── network
│   └── rpms
└── templates

**Comment by jerry817** [comment]
I faced the same issue. 
CentOS Linux release 7.4.1708 (Core)

Stuck at 
(4/6) Start to initialize Kubernetes master...
Exit Status: 1

from log:
kubelet: error: unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory

**Comment by TimothyYe** [comment]
@jerry817  Thanks, I'll try to reproduce this issue.

**Comment by jerry817** [comment]
This issue is resolved after this merge #16 
ref:`kubeadm init --kubernetes-version=v1.8.2`
