### ISSUE TITLE
master节点设备重启之后 居然就不能访问9000端口了

### ISSUE THREAD

**Issue by cf532088799** [Orientsoft/kubekit#12]
之前报的那a无证书的问题，居然多init几次就正常
，但是在设备重启之后居然就不能访问了

**Comment by cf532088799** [comment]
用netstat查看9000端口并没有启用，所有启动的容器或者服务中，存在不是开机启动的吗？估计是服务没有起来，但是在master.sh中并没有看出来有启动哪些服务，有几个问题需要确认一下，
1、这个一键部署kubernetes全是基于容器的话，不用单独起系统服务吗？
2、9000端口对应的服务具体是哪一个，9000是添加节点的，另外一个kubernetes的图形界面，端口号没注意是多少，就是部署pod和那个界面

**Comment by TimothyYe** [comment]
@cf532088799  

1. 9000端口是kubekit监听的端口，kubekit本身并没有设置为随机器启动而启动，需要手动执行 ./kubekit s 重新启动

2. kubernetes dashboard，默认端口31234，README中有提到
