### ISSUE TITLE
断网离线安装不上

### ISSUE THREAD

**Issue by fanhongli** [Orientsoft/kubekit#13]
是不是 echo $HTTP_SERVER storage.googleapis.com >> /etc/hosts 
离线寻找版本导致的？

**Comment by lucker6666** [comment]
kubeadm init --kubernetes-version=v1.8.1 --pod-network-cidr=10.96.0.0/12 
add the --kubernetes-version=v1.8.1

**Comment by lucker6666** [comment]
Sorry , it should be v1.8.2

**Comment by fanhongli** [comment]
i make a mirror docker for dl.k8s.io.mirror

docker run -d -p 443:8443 -p 80:8080 --name dl.k8s.io.mirror  dl.k8s.io.mirror

openssl x509 -inform der -in dl.k8s.io.cer  -out dl.k8s.io.pem

cat dl.k8s.io.pem >> /etc/pki/tls/certs/ca-bundle.crt

echo "127.0.0.1 dl.k8s.io" >> /etc/hosts

**Comment by TimothyYe** [comment]
@fanhongli 之歌mirror docker是用来干嘛的？
