### ISSUE TITLE
(4/6) Start to initialize Kubernetes master... 安装失败

### ISSUE THREAD

**Issue by dengqingpei1990** [Orientsoft/kubekit#18]
如题master节点在初始化kubernetes master时失败，install.log也未能打印出错误信息。

个人猜测：
./kubekit s 启动文件服务后，手动kubeadm init验证，发现有错误信息如下：
```bash
unable to get URL "https://dl.k8s.io/release/stable-1.8.txt": 
Get https://storage.googleapis.com/kubernetes-release/release/stable-1.8.txt: dial tcp 172.217.27.144:443: i/o timeout
```
kubeadm会去`https://storage.googleapis.com/kubernetes-release/release/stable-1.8.txt`下载一个文件，需要有外网网络环境，且需要科学上网姿势。
该文件内容为`v.1.8.3`,建议加入到文件服务中。
另外: 建议把kubeadm执行过程的打印信息也输出至install.log中，方便调试排错，辛苦

**Comment by Graham-Aker** [comment]
遇到了同样的问题， 不过关键的gcr镜像已经有了，后面就手动安装。。

**Comment by TimothyYe** [comment]
感谢你们的反馈，我会近期重现一下

**Comment by Graham-Aker** [comment]
This issue is resolved
ref:kubeadm init --kubernetes-version=v1.8.2

**Comment by dengqingpei1990** [comment]
@Graham-Aker 
已经发现作者已经更新了master.sh脚本，添加了--kubernetes-version=v1.8.2
但是似乎还没有更新到package下载包中，下载下来的master.sh脚本中没有--kubernetes-version=v1.8.2

**Comment by TimothyYe** [comment]
@dengqingpei1990 
@Graham-Aker 

安装包已经更新
