### ISSUE TITLE
The scripts have a problem

### ISSUE THREAD

**Issue by Boxuan666** [Orientsoft/kubekit#2]
When i am run the ./kubekit init master ip, i meet a problem. the code as follow
`Initialization process started, with kubernetes master IP: 6.86.5.20

✔ HTTP file server listening at: 0.0.0.0:8000

Start to install docker engine...
(1/2) Start to install docker...
Exit Status: 2

✖ Failed to install docker engine...

✖ Program terminated...`

**Comment by TimothyYe** [comment]
Hi @Boxuan666 ,

Please show your installation directory structure...
Did you place the kubekit program & installation package at the right place?

**Comment by ayong** [comment]
Start to install docker engine...
(1/2) Start to install docker...
Exit Status: 1

✖ Failed to install docker engine...

✖ Program terminated...

======================================================
#tail install.log
--> 正在处理依赖关系 policycoreutils = 2.5-11.el7_3，它被软件包 policycoreutils-python-2.5-11.el7_3.x86_64 需要
---> 软件包 python-IPy.noarch.0.0.75-6.el7 将被 安装
---> 软件包 setools-libs.x86_64.0.3.3.8-1.1.el7 将被 安装
--> 解决依赖关系完成
 您可以尝试添加 --skip-broken 选项来解决该问题
 您可以尝试执行：rpm -Va --nofiles --nodigest

**Comment by ayong** [comment]
change to a new aliyun ec2,  also failed
--------------------------------------------------------------
Start to install docker engine...
(1/2) Start to install docker...
(2/2) Start to config docker...
Exit Status: 1

鉁Failed to install docker engine...

鉁Program terminated...
--------------------------------------------------------------------
tail -f install.log
--------------------------------------------------
Installed:
  audit-libs-python.x86_64 0:2.6.5-3.el7_3.1                                    
  checkpolicy.x86_64 0:2.5-4.el7                                                
  docker-engine.x86_64 0:1.12.6-1.el7.centos                                    
  docker-engine-selinux.noarch 0:1.12.6-1.el7.centos                            
  libcgroup.x86_64 0:0.41-11.el7                                                
  libseccomp.x86_64 0:2.3.1-2.el7                                               
  libsemanage-python.x86_64 0:2.5-5.1.el7_3                                     
  libtool-ltdl.x86_64 0:2.4.2-22.el7_3                                          
  policycoreutils-python.x86_64 0:2.5-11.el7_3                                  
  python-IPy.noarch 0:0.75-6.el7                                                
  setools-libs.x86_64 0:3.3.8-1.1.el7                                           

Complete!
KUBEKIT_OUTPUT (2/2) Start to config docker...

**Comment by TimothyYe** [comment]
@ayong Install scripts are just updated today, please re-downlaod node.sh, docker.sh from Baidu Yun and try again. BTW, what is the version of CentOS of aliyun ?

**Comment by ayong** [comment]
At aliyun ec2 retry and install successfull,but cant open the 9000 port and 8000 port. telnet refused.
-----------------------------------------------------------------------------------------------------
[root@iZwz99o0w6be3986wdzybrZ kubekit]# ll
total 10972
-rwxr-xr-x 1 root root 11228363 Sep 18 20:31 kubekit
drwxr-xr-x 5 root root     4096 Sep 19 08:17 package
[root@iZwz99o0w6be3986wdzybrZ kubekit]# uname -a
Linux iZwz99o0w6be3986wdzybrZ 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@iZwz99o0w6be3986wdzybrZ kubekit]# telnet localhost 9000
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
Trying ::1...
telnet: connect to address ::1: No route to host
[root@iZwz99o0w6be3986wdzybrZ kubekit]#

**Comment by TimothyYe** [comment]
@ayong  Try to use ```./kubekit s``` it will restart the server.

**Comment by ayong** [comment]
[root@k8s-master kubekit]# ./kubekit s

 ___  __        ___  ___      ________      _______       ___  __        ___      _________   
|\  \|\  \     |\  \|\  \    |\   __  \    |\  ___ \     |\  \|\  \     |\  \    |\___   ___\ 
\ \  \/  /|_   \ \  \\\  \   \ \  \|\ /_   \ \   __/|    \ \  \/  /|_   \ \  \   \|___ \  \_| 
 \ \   ___  \   \ \  \\\  \   \ \   __  \   \ \  \_|/__   \ \   ___  \   \ \  \       \ \  \  
  \ \  \\ \  \   \ \  \\\  \   \ \  \|\  \   \ \  \_|\ \   \ \  \\ \  \   \ \  \       \ \  \ 
   \ \__\\ \__\   \ \_______\   \ \_______\   \ \_______\   \ \__\\ \__\   \ \__\       \ \__\
    \|__| \|__|    \|_______|    \|_______|    \|_______|    \|__| \|__|    \|__|        \|__|


KubeKit V0.1.1 鈸 OrientSoft 2017


鉁HTTP file server listening at: 0.0.0.0:8000

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /assets/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] HEAD   /assets/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
panic: html/template: pattern matches no files: `templates/*`

goroutine 1 [running]:
html/template.Must(0x0, 0xb101c0, 0xc4201ac0d0, 0xb101c0)
        /usr/local/Cellar/go/1.9/libexec/src/html/template/template.go:364 +0x54
github.com/gin-gonic/gin.(*Engine).LoadHTMLGlob(0xc4201aa0e0, 0x8dcc57, 0xb)
        /Users/timothy/workspace/src/github.com/gin-gonic/gin/gin.go:126 +0x6b
github.com/Orientsoft/kubekit/controllers.StartToolkitServer(0x8d7d86, 0x5, 0x8d7d90, 0x5)
        /Users/timothy/workspace/src/github.com/Orientsoft/kubekit/controllers/router.go:25 +0x87
main.main.func3(0xc4201603c0, 0x0, 0x0)
        /Users/timothy/workspace/src/github.com/Orientsoft/kubekit/main.go:90 +0x12a
gopkg.in/urfave/cli%2ev1.HandleAction(0x83e780, 0x8f8fc8, 0xc4201603c0, 0xc42004eb00, 0x0)
        /Users/timothy/workspace/src/gopkg.in/urfave/cli.v1/app.go:485 +0xd2
gopkg.in/urfave/cli%2ev1.Command.Run(0x8d9609, 0x6, 0x0, 0x0, 0xc420041ef0, 0x1, 0x1, 0x8ec6e3, 0x2b, 0x0, ...)
        /Users/timothy/workspace/src/gopkg.in/urfave/cli.v1/command.go:193 +0xa99
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc42005d520, 0xc42000a060, 0x2, 0x2, 0x0, 0x0)
        /Users/timothy/workspace/src/gopkg.in/urfave/cli.v1/app.go:250 +0x758
main.main()
        /Users/timothy/workspace/src/github.com/Orientsoft/kubekit/main.go:96 +0x2a0
[root@k8s-master kubekit]# telnet localhost 8000
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
Trying ::1...
telnet: connect to address ::1: No route to host
[root@k8s-master kubekit]#

**Comment by TimothyYe** [comment]
@ayong  It looks like that "templates/" directory is missing...

**Comment by TimothyYe** [comment]
@ayong Sorry, templates/ & assets/ are missing, I'll update v0.1.1 release, you need to re-download it.

**Comment by TimothyYe** [comment]
@ayong Release V0.1.1 updated, please re-download it, thanks!

**Comment by ayong** [comment]
Thanks
