### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by Chenwei09** [Orientsoft/kubekit#20]
Initialization process started, with kubernetes master IP: 10.2.21.197

â HTTP file server listening at: 0.0.0.0:8000

Start to install docker engine...
(1/2) Start to install docker...

â Docker engine installed...

Start to initialize Kubernetes master node...

(1/6) Start to load images for Kubernetes master...
(2/6) Start to install components for Kubernetes master...
(3/6) Start to configure firewall...
(4/6) Start to initialize Kubernetes master...
Exit Status: 2

â Failed to initialize Kubernetes master node...
-------------------------------------------------------------
安装日志
KUBEKIT_OUTPUT (1/6) Start to load images for Kubernetes master...
Loaded image: gcr.io/google_containers/etcd-amd64:3.0.17
Loaded image: quay.io/coreos/flannel:v0.8.0-amd64
Loaded image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3
KUBEKIT_OUTPUT (2/6) Start to install components for Kubernetes master...
KUBEKIT_OUTPUT (3/6) Start to configure firewall...
KUBEKIT_OUTPUT (4/6) Start to initialize Kubernetes master...
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[init] Using Kubernetes version: v1.7.2
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks

**Comment by TimothyYe** [comment]
@Chenwei09 可以打开master.sh，找到如下两句命令：

    export KUBE_ETCD_IMAGE=gcr.io/google_containers/etcd-amd64:3.0.17
    kubeadm init --kubernetes-version=v1.8.2 --pod-network-cidr=10.96.0.0/12

直接在master节点上运行，如果还报错，应该能看到具体的错误信息

**Comment by Chenwei09** [comment]
@TimothyYe 感谢！在执行你的那两句报错后，通过错误日志找到解决方案，1. [preflight] Some fatal errors occurred:
    /proc/sys/net/bridge/bridge-nf-call-iptables contents are not set to 1
解决方案：
        echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables
        echo 1 > /proc/sys/net/bridge/bridge-nf-call-ip6tables
在执行就成功了。

**Comment by TimothyYe** [comment]
@Chenwei09 谢谢你的反馈，我会再优化一下脚本
