### ISSUE TITLE
✖ Failed to install docker engine...  ✖ Program terminated...

### ISSUE THREAD

**Issue by liqingw001** [Orientsoft/kubekit#21]
CentOS 7.4.1708
![image](https://user-images.githubusercontent.com/34803156/34354577-4621cfda-ea6a-11e7-8ae0-d6809add7d37.png)

install.log:
KUBEKIT_OUTPUT (2/2) Start to config docker...

**Comment by TimothyYe** [comment]
@liqingw001 看看install.log中有什么输出没有

**Comment by liqingw001** [comment]
install.log的输出就到“KUBEKIT_OUTPUT（2/2）开始配置docker ...”，docker.sh里注释掉44行就ok了

**Comment by TimothyYe** [comment]
@liqingw001 44行就是配置docker，关闭selinux和firewalld的，不过为啥会报错呢

**Comment by TimothyYe** [comment]
后续我可以更新一下脚本，应该能避免这样的报错

**Comment by starjason** [comment]
如果系统中已安装了docker，需要先把docker卸载了，否则无法进行下去。

**Comment by TimothyYe** [comment]
@starjason 之前安装的docker版本是多少？

**Comment by starjason** [comment]
@TimothyYe centos7.3系统 利用yum 直接安装的是 12.6的版本

**Comment by TimothyYe** [comment]
离线包，也得下载支持CentOS7.3的才行哦
