### ISSUE TITLE
在master执行命令错误

### ISSUE THREAD

**Issue by Chenwei09** [Orientsoft/kubekit#22]
在msater已执行source ~/.bashrc，
[root@k8s-node0 yum]# kubectl get rc
Error from server (Forbidden): User "system:node:k8s-node0" cannot list replicationcontrollers in the namespace "default". (get replicationcontrollers)

[root@k8s-node0 yum]# kubectl create -f heapster.yaml
Error from server (Forbidden): error when creating "heapster.yaml": User "system:node:k8s-node0" cannot create serviceaccounts in the namespace "kube-system". (post serviceaccounts)
Error from server (Forbidden): error when creating "heapster.yaml": User "system:node:k8s-node0" cannot create deployments.extensions in the namespace "kube-system". (post deployments.extensions)
Error from server (Forbidden): error when creating "heapster.yaml": User "system:node:k8s-node0" cannot create services in the namespace "kube-system". (post services)

**Comment by TimothyYe** [comment]
试试先

```bash
 export KUBECONFIG=/etc/kubernetes/admin.conf
```
然后再运行命令
