### ISSUE TITLE
Redhat 7.2 安装报错

### ISSUE THREAD

**Issue by ChuckyThh** [Orientsoft/kubekit#25]
KubeKit V0.2 ⓒ  OrientSoft 2017

Initialization process started, with kubernetes master IP: 192.168.208.79

✔ HTTP file server listening at: 0.0.0.0:8000

Start to install docker engine...
(1/2) Start to install docker...

✔ Docker engine installed...

Start to initialize Kubernetes master node...

(1/6) Start to load images for Kubernetes master...
Exit Status: 52

✖ Failed to initialize Kubernetes master node...

Httpserver: ListenAndServe() error: http: Server closed

**Comment by TimothyYe** [comment]
Redhat 7.2还未进行测试，最好用当前支持的操作系统哦

**Comment by ChuckyThh** [comment]
已经解决了，不是系统问题，而是用了高版本的docker，导致的兼容问题。
