### ISSUE TITLE
该版本里集成了cAdvisor吗？

### ISSUE THREAD

**Issue by ChuckyThh** [Orientsoft/kubekit#27]
看到官方介绍，都是自带有cAdvisor监控工具的，应该怎么唤起？

**Comment by TimothyYe** [comment]
我也看到官方之前说有集成cAdvisor，不过集成安装了最新的V1.9.2，好像也没找到。
监控建议装heapster套件……

**Comment by ChuckyThh** [comment]
我在安装heapster上去后，查看日志报错：
E0201 10:33:50.081467       1 reflector.go:190] k8s.io/heapster/metrics/heapster.go:322: Failed to list *v1.Pod: User "system:serviceaccount:kube-system:heapster" cannot list pods at the cluster scope. (get pods)
E0201 10:33:50.109868       1 reflector.go:190] k8s.io/heapster/metrics/util/util.go:51: Failed to list *v1.Node: User "system:serviceaccount:kube-system:heapster" cannot list nodes at the cluster scope. (get nodes)
E0201 10:33:50.556426       1 reflector.go:190] k8s.io/heapster/metrics/util/util.go:51: Failed to list *v1.Node: User "system:serviceaccount:kube-system:heapster" cannot list nodes at the cluster scope. (get nodes)
E0201 10:33:51.096982       1 reflector.go:190] k8s.io/heapster/metrics/util/util.go:51: Failed to list *v1.Node: User "system:serviceaccount:kube-system:heapster" cannot list nodes at the cluster scope. (get nodes)
E0201 10:33:51.097548       1 reflector.go:190] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Failed to list *v1.Namespace: User "system:serviceaccount:kube-system:heapster" cannot list namespaces at the cluster scope. (get namespaces)

看到网上说，heapster通过kubelet里面的cadvisor获取容器的监控信息。不知道是不是因为缺少cAdvisor而造成？
还有就是。。。中文版的Kube Dashboard是不是缺少了一些选项栏？还是说安装heapster后才有那个监控状态的workloads>pods？

**Comment by ChuckyThh** [comment]
附上我在[https://www.jianshu.com/p/3f803cd02d74](url)看的安装heapster教程

**Comment by TimothyYe** [comment]
heapster还需要单独下载和导入几个镜像，然后再单独创建

**Comment by ChuckyThh** [comment]
Kubekit使用8000作为文件服务监听端口号 这个8000端口是做什么用的？

**Comment by TimothyYe** [comment]
安装时候，node上用来从master下载文件用的

**Comment by ChuckyThh** [comment]
哦哦好的呐，我还有问题哦，我在安装heapster 时失败，看到网上说要替换source=kubernetes:https://kubernetes.default，使用非insecure-port连接，即master主机ip+apiserver的8080端口，可是我改了不行，k8s的apiserver端口应该是什么呀？

**Comment by ChuckyThh** [comment]
似乎这样不行

Using Kubernetes client with master "https://192.168.23.160:6443" and version v1
I0206 09:08:04.356687       1 configs.go:62] Using kubelet port 10255
E0206 09:08:04.380041       1 kubelet.go:336] Failed to load nodes: User "system:serviceaccount:kube-system:heapster" cannot list nodes at the cluster scope. (get nodes)

在网上几乎查不到相关的错误

**Comment by ChuckyThh** [comment]
原因找到了，是因为缺少了RBAC授权，授权后安装成功，可是dashboard1.6.3依旧朴素没有相关的UI监控画面，最后只能通过grafana来看到集群的相关图形信息。。。心累。。。
