### ISSUE TITLE
Language Preference

### ISSUE THREAD

**Issue by coolpalani** [Orientsoft/kubekit#29]
Can I choose English while I install the K8s

**Comment by TimothyYe** [comment]
@coolpalani Good suggestion, in the later release I'll refactor kubekit UI and let it support i18n.

**Comment by coolpalani** [comment]
if you deliver in universal language, it would be more help to all.
Thanks for understand.
I am looking forward your next release.

**Comment by TimothyYe** [comment]
@coolpalani  V0.3 is released just now with i18n support, you can refer to [https://github.com/Orientsoft/kubekit/releases/tag/V0.3](https://github.com/Orientsoft/kubekit/releases/tag/V0.3)
