### ISSUE TITLE
启动后Web UI Portal 9000 端口可以访问，但是Kubernetes Dashboar不能访问31234 端口无进程

### ISSUE THREAD

**Issue by alive-mou** [Orientsoft/kubekit#34]
只有一下警告日志，不知是否影响

[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /assets/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
[GIN-debug] HEAD   /assets/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
[GIN-debug] Loaded HTML Templates (3): 
	- index.html
	- locale.html
	- 

open ./.nodes: no such file or directory
[GIN-debug] GET    /                         --> github.com/Orientsoft/kubekit/controllers.(*MainRouter).IndexHandler-fm (4 handlers)
[GIN-debug] GET    /ws                       --> github.com/Orientsoft/kubekit/controllers.(*MainRouter).Initialize.func1 (4 handlers)
[GIN-debug] GET    /node/list                --> github.com/Orientsoft/kubekit/controllers.(*MainRouter).ListNodesHandler-fm (4 handlers)
[GIN-debug] POST   /node                     --> github.com/Orientsoft/kubekit/controllers.(*MainRouter).CreateNodeHandler-fm (4 handlers)
[GIN-debug] PUT    /node/remove/:id          --> github.com/Orientsoft/kubekit/controllers.(*MainRouter).RemoveNodeHandler-fm (4 handlers)
[GIN-debug] GET    /node/refresh/:id         --> github.com/Orientsoft/kubekit/controllers.(*MainRouter).RefreshNodeHandler-fm (4 handlers)
[GIN-debug] GET    /node/log/:id             --> github.com/Orientsoft/kubekit/controllers.(*MainRouter).GetInstallLog-fm (4 handlers)
[GIN-debug] POST   /install                  --> github.com/Orientsoft/kubekit/controllers.(*MainRouter).InstallNodeHandler-fm (4 handlers)
[GIN-debug] GET    /install/progress/:id/:step --> github.com/Orientsoft/kubekit/controllers.(*MainRouter).NodeProgressHandler-fm (4 handlers)

**Comment by D-Lover** [comment]
大哥哥。。

**Comment by TimothyYe** [comment]
应该是面版未启动运行，得看看面版的日志

**Comment by D-Lover** [comment]
面板日志在那个文件夹哦？/var/log?

**Comment by D-Lover** [comment]
顺便提一下。安装过程中出现无法启动
✖ Failed to initialize Kubernetes master node...

查看日志提示
Configuration file /etc/systemd/system/kubelet.service is marked executable. Please remove executable permission bits. Proceeding anyway.

应该和ipv6有关。按照网上的关闭了ipve6出现的，换台机子就好了。。。

**Comment by D-Lover** [comment]
原来是启动的有点慢。。。。

**Comment by D-Lover** [comment]
web ui 可以切换为英文嘛？
