### ISSUE TITLE
能否添加ssh免密码登录?

### ISSUE THREAD

**Issue by cooljsz** [Orientsoft/kubekit#5]
正好要搭建一套k8s的环境,看到这个项目真的很振奋.
感谢作者的开源.
另,有计划支持kubespray吗?

**Comment by TimothyYe** [comment]
@cooljsz 免密登录这个可以有，程序需要改动一下
kubespray空了我再了解一下

**Comment by cooljsz** [comment]
感谢你对公众意见的态度,谢谢你的付出.
