### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by cooljsz** [Orientsoft/kubekit#7]
KubeKit V0.2 ⓒ  OrientSoft 2017

Initialization process started, with kubernetes master IP: 172.16.4.50

✔ HTTP file server listening at: 0.0.0.0:8000

Start to install docker engine...
(1/2) Start to install docker...
Exit Status: 1

✖ Failed to install docker engine...

✖ Program terminated...
文件目录结构如下
![image](https://user-images.githubusercontent.com/1953380/32133779-81918b5a-bc11-11e7-9ba2-ad1335a2805e.png)

**Comment by cooljsz** [comment]
KUBEKIT_OUTPUT (1/2) Start to install docker...
Loaded plugins: fastestmirror
Examining /tmp/docker/audit-2.6.5-3.el7_3.1.x86_64.rpm: audit-2.6.5-3.el7_3.1.x86_64
/tmp/docker/audit-2.6.5-3.el7_3.1.x86_64.rpm: does not update installed package.
Examining /tmp/docker/audit-libs-2.6.5-3.el7_3.1.x86_64.rpm: audit-libs-2.6.5-3.el7_3.1.x86_64
/tmp/docker/audit-libs-2.6.5-3.el7_3.1.x86_64.rpm: does not update installed package.
Examining /tmp/docker/audit-libs-python-2.6.5-3.el7_3.1.x86_64.rpm: audit-libs-python-2.6.5-3.el7_3.1.x86_64
Marking /tmp/docker/audit-libs-python-2.6.5-3.el7_3.1.x86_64.rpm to be installed
Examining /tmp/docker/checkpolicy-2.5-4.el7.x86_64.rpm: checkpolicy-2.5-4.el7.x86_64
Marking /tmp/docker/checkpolicy-2.5-4.el7.x86_64.rpm to be installed
Examining /tmp/docker/docker-engine-1.12.6-1.el7.centos.x86_64.rpm: docker-engine-1.12.6-1.el7.centos.x86_64
Marking /tmp/docker/docker-engine-1.12.6-1.el7.centos.x86_64.rpm to be installed
Examining /tmp/docker/docker-engine-selinux-1.12.6-1.el7.centos.noarch.rpm: docker-engine-selinux-1.12.6-1.el7.centos.noarch
Marking /tmp/docker/docker-engine-selinux-1.12.6-1.el7.centos.noarch.rpm to be installed
Examining /tmp/docker/libcgroup-0.41-11.el7.x86_64.rpm: libcgroup-0.41-11.el7.x86_64
Marking /tmp/docker/libcgroup-0.41-11.el7.x86_64.rpm to be installed
Examining /tmp/docker/libseccomp-2.3.1-2.el7.x86_64.rpm: libseccomp-2.3.1-2.el7.x86_64
Marking /tmp/docker/libseccomp-2.3.1-2.el7.x86_64.rpm to be installed
Examining /tmp/docker/libsemanage-2.5-5.1.el7_3.x86_64.rpm: libsemanage-2.5-5.1.el7_3.x86_64
/tmp/docker/libsemanage-2.5-5.1.el7_3.x86_64.rpm: does not update installed package.
Examining /tmp/docker/libsemanage-python-2.5-5.1.el7_3.x86_64.rpm: libsemanage-python-2.5-5.1.el7_3.x86_64
Marking /tmp/docker/libsemanage-python-2.5-5.1.el7_3.x86_64.rpm to be installed
Examining /tmp/docker/libtool-ltdl-2.4.2-22.el7_3.x86_64.rpm: libtool-ltdl-2.4.2-22.el7_3.x86_64
/tmp/docker/libtool-ltdl-2.4.2-22.el7_3.x86_64.rpm: does not update installed package.
Examining /tmp/docker/policycoreutils-2.5-11.el7_3.x86_64.rpm: policycoreutils-2.5-11.el7_3.x86_64
/tmp/docker/policycoreutils-2.5-11.el7_3.x86_64.rpm: does not update installed package.
Examining /tmp/docker/policycoreutils-python-2.5-11.el7_3.x86_64.rpm: policycoreutils-python-2.5-11.el7_3.x86_64
Marking /tmp/docker/policycoreutils-python-2.5-11.el7_3.x86_64.rpm to be installed
Examining /tmp/docker/python-IPy-0.75-6.el7.noarch.rpm: python-IPy-0.75-6.el7.noarch
Marking /tmp/docker/python-IPy-0.75-6.el7.noarch.rpm to be installed
Examining /tmp/docker/setools-libs-3.3.8-1.1.el7.x86_64.rpm: setools-libs-3.3.8-1.1.el7.x86_64
Marking /tmp/docker/setools-libs-3.3.8-1.1.el7.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package audit-libs-python.x86_64 0:2.6.5-3.el7_3.1 will be installed
--> Processing Dependency: audit-libs(x86-64) = 2.6.5-3.el7_3.1 for package: audit-libs-python-2.6.5-3.el7_3.1.x86_64
Loading mirror speeds from cached hostfile
 * base: mirrors.btte.net
 * extras: mirrors.btte.net
 * updates: mirrors.btte.net
---> Package checkpolicy.x86_64 0:2.5-4.el7 will be installed
---> Package docker-engine.x86_64 0:1.12.6-1.el7.centos will be installed
---> Package docker-engine-selinux.noarch 0:1.12.6-1.el7.centos will be installed
---> Package libcgroup.x86_64 0:0.41-11.el7 will be installed
---> Package libseccomp.x86_64 0:2.3.1-2.el7 will be installed
---> Package libsemanage-python.x86_64 0:2.5-5.1.el7_3 will be installed
--> Processing Dependency: libsemanage = 2.5-5.1.el7_3 for package: libsemanage-python-2.5-5.1.el7_3.x86_64
---> Package policycoreutils-python.x86_64 0:2.5-11.el7_3 will be installed
--> Processing Dependency: policycoreutils = 2.5-11.el7_3 for package: policycoreutils-python-2.5-11.el7_3.x86_64
---> Package python-IPy.noarch 0:0.75-6.el7 will be installed
---> Package setools-libs.x86_64 0:3.3.8-1.1.el7 will be installed
--> Finished Dependency Resolution
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by TimothyYe** [comment]
@cooljsz 请问系统是什么版本？是否是干净系统？

**Comment by cooljsz** [comment]
centos7 1708 最小化安装,之后装了ntp和openssl

**Comment by cooljsz** [comment]
[root@docker1 package]# ./docker.sh 172.16.4.50
+ set -e
+ HTTP_SERVER=
++ id -u
+ root=0
+ '[' 0 -ne 0 ']'
+ main 172.16.4.50
+ HTTP_SERVER=172.16.4.50
+ kube::install_docker
+ echo 'KUBEKIT_OUTPUT (1/2) Start to install docker...'
KUBEKIT_OUTPUT (1/2) Start to install docker...
+ set +e
+ which docker-compose
+ i=0
+ set -e
+ '[' 0 -ne 0 ']'
+ set +e
+ which docker
+ j=1
+ set -e
+ '[' 1 -ne 0 ']'
+ curl -L http://172.16.4.50/rpms/docker.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to 172.16.4.50:80; Connection refused

**Comment by cooljsz** [comment]
手动安装组件之后卡在4/6了
[root@docker1 kubekit]# ./kubekit init 172.16.4.50

 ___  __        ___  ___      ________      _______       ___  __        ___      _________   
|\  \|\  \     |\  \|\  \    |\   __  \    |\  ___ \     |\  \|\  \     |\  \    |\___   ___\ 
\ \  \/  /|_   \ \  \\\  \   \ \  \|\ /_   \ \   __/|    \ \  \/  /|_   \ \  \   \|___ \  \_| 
 \ \   ___  \   \ \  \\\  \   \ \   __  \   \ \  \_|/__   \ \   ___  \   \ \  \       \ \  \  
  \ \  \\ \  \   \ \  \\\  \   \ \  \|\  \   \ \  \_|\ \   \ \  \\ \  \   \ \  \       \ \  \ 
   \ \__\\ \__\   \ \_______\   \ \_______\   \ \_______\   \ \__\\ \__\   \ \__\       \ \__\
    \|__| \|__|    \|_______|    \|_______|    \|_______|    \|__| \|__|    \|__|        \|__|


KubeKit V0.2 ⓒ  OrientSoft 2017

Initialization process started, with kubernetes master IP: 172.16.4.50

✔ HTTP file server listening at: 0.0.0.0:8000

Start to install docker engine...
(1/2) Start to install docker...

✔ Docker engine installed...

Start to initialize Kubernetes master node...

(1/6) Start to load images for Kubernetes master...
(2/6) Start to install components for Kubernetes master...
(3/6) Start to configure firewall...
(4/6) Start to initialize Kubernetes master...

**Comment by cwchen** [comment]
1708不行，docker的安装包和他的依赖包都是离线的，在1708中，这些依赖都升级了，最好的办法是只留下docker1.12.6的包，其余的都删除，yum localinstall下这个docker的包就行
在安装过程中，需要对docker进行配置，程序中已经进行了自动化的配置，如果手动安装，记得加上这些配置，否则的话后续安装会出现问题

**Comment by TimothyYe** [comment]
@cwchen @cooljsz 我这里暂时还没有可用的1708的系统，如果是1708中，依赖包进行了升级，需要重新制作针对1708的离线安装包并打包，才能支持1708的系统

**Comment by cooljsz** [comment]
yum install docker checkpolicy libcgroup libseccomp libsemanage-python -y
Package 2:docker-1.12.6-61.git85d7426.el7.centos.x86_64 
Package checkpolicy-2.5-4.el7.x86_64
Package libcgroup-0.41-13.el7.x86_64
Package libseccomp-2.3.1-3.el7.x86_64
Package libsemanage-python-2.5-8.el7.x86_64

**Comment by cooljsz** [comment]
@cwchen 怎么手动配置docker?

**Comment by cwchen** [comment]
sed -i -e 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
 
    #sysctl -w net.bridge.bridge-nf-call-iptables=1
    #sysctl -w net.bridge.bridge-nf-call-ip6tables=1
    # /etc/sysctl.conf 
    # net.bridge.bridge-nf-call-ip6tables = 1
    # net.bridge.bridge-nf-call-iptables = 1
     
    set +e
    which firewalld
    j=$?
    set -e
 
    if [ $j -eq 0 ]; then
    systemctl disable firewalld
    systemctl stop firewalld
    fi
 
    echo DOCKER_STORAGE_OPTIONS=\" -s overlay --selinux-enabled=false\" > /etc/sysconfig/docker-storage

**Comment by cooljsz** [comment]
感谢@cwchen 我试试
另,如果在4/6步骤出问题想重新执行的话,需要执行kubeadm reset命令,这个可以写到文档里.

**Comment by cooljsz** [comment]
重新使用1611的centos7安装成功了,感谢二位@cwchen @TimothyYe

**Comment by TimothyYe** [comment]
@cooljsz 感谢你的关注，1708兼容性还没进行测试，如果是离线包版本的问题，我会最近开始测试，争取打包兼容1708的离线包出来

**Comment by TimothyYe** [comment]
CentOS 7.4 1708 已支持

**Comment by cooljsz** [comment]
太棒了,感谢
