### ISSUE TITLE
发现未知ip10.96.0.1

### ISSUE THREAD

**Issue by cooljsz** [Orientsoft/kubekit#8]
[certificates] API Server serving cert is signed for DNS names [docker1.xxx.com kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 172.16.4.50]

**Comment by TimothyYe** [comment]
这是在初始化k8s集群的时候，安装脚本默认指定的集群内部IP

参考：

https://github.com/Orientsoft/kubekit/blob/master/shells/master.sh#L111

**Comment by cooljsz** [comment]
ok,thx
