### ISSUE TITLE
能否添加ssl相关配置?

### ISSUE THREAD

**Issue by cooljsz** [Orientsoft/kubekit#9]
局域网内部部署的时候能否自动设置ca证书.这个对我们来说太有用了

**Comment by TimothyYe** [comment]
@cooljsz 你好， 部署过后的api server已经启用了SSL，节点join的时候，也是通过SSL的方式，你可以通过浏览器访问master节点 https://192.168.x.x:6443/api 浏览器默认会提示证书未认证

**Comment by TimothyYe** [comment]
@cooljsz 私有签发的证书都是被显示威未认证的，除非购买付费证书。搭建Harbor，你可以单独生成Harbor自己用的证书，跟K8S这个证书不影响的。K8S的master和各个node，到时候需要把Harbor的根证书设置为可信任的即可。

**Comment by cooljsz** [comment]
"K8S的master和各个node，到时候需要把Harbor的根证书设置为可信任的即可。"这个该怎么设置可信呢?

**Comment by TimothyYe** [comment]
@cooljsz 

拷贝harbor生成证书的跟证书，到K8S每个节点的如下位置：
cp ca.crt /etc/pki/ca-trust/source/anchors/harbor.crt

然后，CentOS中运行命令：
update-ca-trust

将跟证书设置为可信任
